#pragma once
#define PS2_PORT_COMMAND 0x64
#define PS2_PORT_DATA 0x60

#define PS2_CMD_READ_CONFIG 0x20
#define PS2_CMD_WRITE_CONFIG 0x60
#define PS2_CMD_DISABLE_FIRST 0xad
#define PS2_CMD_DISABLE_SECOND 0xa7
#define PS2_CMD_ENABLE_FIRST 0xae

#define PS2_CONFIG_FIRST_INT 1
#define PS2_CONFIG_SECOND_INT 2
#define PS2_CONFIG_TRANSLATION 0x40

#define PS2_STATUS_OUTPUT 1
#define PS2_STATUS_INPUT 2

#define PS2_DEVICE_SET_LEDS 0xed
#define PS2_DEVICE_RESET 0xff

#define PS2_RESPONSE_ACK 0xfa
#define PS2_RESPONSE_RESEND 0xfe
#define PS2_RESPONSE_RESET 0xaa
#define PS2_RESPONSE_RESET_FAILED 0xfc

#define PS2_LED_NUM_LOCK 2
#define PS2_LED_CAPS_LOCK 4
