#pragma once
#include <ipc.h>
#define IPC_ACPID_POWER_STATE 0
#define IPC_FBD_INFO 0
#define IPC_FBD_COPY IPC_CALL_MEMORY_SHARING
#define IPC_PCID_ACCESS 0
#define IPC_DEVD_REGISTER IPC_CALL_MEMORY_SHARING + 2
#define IPC_VFSD_CLOSE 0
#define IPC_VFSD_SEEK 1
#define IPC_VFSD_CLONE_FDS 2
#define IPC_VFSD_OPEN IPC_CALL_MEMORY_SHARING
#define IPC_VFSD_MOUNT IPC_CALL_MEMORY_SHARING + 1
#define IPC_VFSD_WRITE IPC_CALL_MEMORY_SHARING + 2
#define IPC_VFSD_FINISH_MOUNT IPC_CALL_MEMORY_SHARING + 3
#define IPC_VFSD_READ IPC_CALL_MEMORY_SHARING_RW
#define IPC_VFSD_FS_OPEN IPC_CALL_MEMORY_SHARING
#define IPC_VFSD_FS_WRITE IPC_CALL_MEMORY_SHARING + 1
#define IPC_VFSD_FS_READ IPC_CALL_MEMORY_SHARING_RW
#define IPC_VFSD_FS_STAT IPC_CALL_MEMORY_SHARING_RW + 1
#define IPC_ARGD_GET_NUM 0
#define IPC_ARGD_GET_SIZE 1
#define IPC_ARGD_ADD IPC_CALL_MEMORY_SHARING
#define IPC_ARGD_GET IPC_CALL_MEMORY_SHARING_RW
#define IPC_ENVD_GET_NUM 0
#define IPC_ENVD_GET_SIZE 1
#define IPC_ENVD_ADD IPC_CALL_MEMORY_SHARING
#define IPC_ENVD_GET IPC_CALL_MEMORY_SHARING_RW
#define IPC_KBDD_KEYPRESS 0
#define IPC_KBDD_REGISTER 1
#define IPC_KBDD_CHANGE_LAYOUT 2
#define IPC_LOGD_REGISTER 0
#define IPC_LOGD_LOG IPC_CALL_MEMORY_SHARING
#define IPC_TTYD_KEY_EVENT 0
