#include <keyboard.h>

const int scancode_conversion[256] = {
    KEY_UNKNOWN,
    KEY_F9,
    KEY_UNKNOWN,
    KEY_F5,
    KEY_F3,
    KEY_F1,
    KEY_F2,
    KEY_F12,
    KEY_UNKNOWN,
    KEY_F10,
    KEY_F8,
    KEY_F6,
    KEY_F4,
    KEY_TAB,
    KEY_BACKTICK,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_LALT,
    KEY_LSHIFT,
    KEY_UNKNOWN,
    KEY_LCONTROL,
    KEY_Q,
    KEY_1,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_Z,
    KEY_S,
    KEY_A,
    KEY_W,
    KEY_2,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_C,
    KEY_X,
    KEY_D,
    KEY_E,
    KEY_4,
    KEY_3,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_SPACE,
    KEY_V,
    KEY_F,
    KEY_T,
    KEY_R,
    KEY_5,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_N,
    KEY_B,
    KEY_H,
    KEY_G,
    KEY_Y,
    KEY_6,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_M,
    KEY_J,
    KEY_U,
    KEY_7,
    KEY_8,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_COMMA,
    KEY_K,
    KEY_I,
    KEY_O,
    KEY_0,
    KEY_9,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_PERIOD,
    KEY_SLASH,
    KEY_L,
    KEY_SEMICOLON,
    KEY_P,
    KEY_DASH,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_QUOTE,
    KEY_UNKNOWN,
    KEY_BRACKET_OPENING,
    KEY_EQUALS,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_CAPS_LOCK,
    KEY_RSHIFT,
    KEY_ENTER,
    KEY_BRACKET_CLOSING,
    KEY_UNKNOWN,
    KEY_BACKSLASH,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_INTERNATIONAL,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_BACKSPACE,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_NUM_1,
    KEY_UNKNOWN,
    KEY_NUM_4,
    KEY_NUM_7,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_NUM_0,
    KEY_NUM_PERIOD,
    KEY_NUM_2,
    KEY_NUM_5,
    KEY_NUM_6,
    KEY_NUM_8,
    KEY_ESCAPE,
    KEY_NUM_LOCK,
    KEY_F11,
    KEY_NUM_PLUS,
    KEY_NUM_3,
    KEY_NUM_DASH,
    KEY_NUM_ASTERISK,
    KEY_NUM_9,
    KEY_SCROLL_LOCK,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_UNKNOWN,
    KEY_F7};
int scancode_conversion_extended[256] = {
    [0x11] = KEY_RALT,
    [0x14] = KEY_RCONTROL,
    [0x1f] = KEY_LSUPER,
    [0x27] = KEY_RSUPER,
    [0x2f] = KEY_MENU,
    [0x4a] = KEY_NUM_SLASH,
    [0x5a] = KEY_NUM_ENTER,
    [0x69] = KEY_END,
    [0x6b] = KEY_ARROW_DOWN,
    [0x6c] = KEY_HOME,
    [0x70] = KEY_INSERT,
    [0x71] = KEY_DELETE,
    [0x72] = KEY_ARROW_DOWN,
    [0x74] = KEY_ARROW_RIGHT,
    [0x75] = KEY_ARROW_UP,
    [0x7a] = KEY_PAGE_DOWN,
    [0x7c] = KEY_PRINT_SCREEN,
    [0x7d] = KEY_PAGE_UP};
