name: CI
on: [push, pull_request]
jobs:
  toolchain:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: sudo apt-get update && sudo apt-get install -y ninja-build
      - name: Install dependencies (macOS)
        if: ${{ matrix.os == 'macos-11' }}
        run: brew install ninja
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v2
        with:
          key: toolchain-${{ matrix.os }}-${{ hashFiles('tools/Makefile') }}
          path: tools/toolchain
      - name: Build toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make toolchain
      - name: Clean toolchain directory
        run: make clean
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: toolchain
    steps:
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86 mtools
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          key: toolchain-${{ matrix.os }}-${{ hashFiles('tools/Makefile') }}
          path: tools/toolchain
      - name: Build OS
        run: make build -j2
      - name: Build OS image with GRUB
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: make build-grub -j2
      - name: Test OS
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        timeout-minutes: 1
        run: |
          sed -i "s/loader.bin/loader.bin ci/" grub.cfg
          make run-grub-nographic
  style:
    runs-on: ubuntu-20.04
    needs: toolchain
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          key: toolchain-ubuntu-20.04-${{ hashFiles('tools/Makefile') }}
          path: tools/toolchain
      - name: Format code
        run: make format
      - name: Check if there are any changes
        run: git diff --exit-code
  analyze:
    runs-on: ubuntu-20.04
    needs: toolchain
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y mtools
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          key: toolchain-ubuntu-20.04-${{ hashFiles('tools/Makefile') }}
          path: tools/toolchain
      - name: Analyze
        run: make analyze -j2
