name: CI
on: [push, pull_request]
jobs:
  toolchain:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: sudo apt-get update && sudo apt-get install -y ninja-build
      - name: Install dependencies (macOS)
        if: ${{ matrix.os == 'macos-11' }}
        run: brew install ninja
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v2
        with:
          key: toolchain-${{ matrix.os }}-${{ hashFiles('tools/Makefile') }}
          path: tools/toolchain
      - name: Build toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make toolchain
      - name: Clean toolchain directory
        run: make clean
  multiboot:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: toolchain
    steps:
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86 mtools
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          key: toolchain-${{ matrix.os }}-${{ hashFiles('tools/Makefile') }}
          path: tools/toolchain
      - name: Build OS
        run: make build-multiboot -j2
      - name: Build OS image with GRUB
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: make build-grub -j2
      - name: Upload loader-mb
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: loader-mb
          path: boot/boot/loader.bin
      - name: Upload kernel
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: kernel
          path: boot/boot/kernel.bin
      - name: Upload init
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: init
          path: boot/boot/init
      - name: Upload drivers
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: drivers
          path: |
            boot/boot/atad
            boot/boot/pcid
      - name: Upload servers
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: servers
          path: |
            boot/boot/argd
            boot/boot/ipcd
            boot/boot/logd
      - name: Upload filesystems
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: filesystems
          path: |
            boot/boot/lvmd
            boot/boot/mbrd
            boot/boot/svfsd
            boot/boot/vfsd
      - name: Upload loadelf
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: lelf
          path: boot/boot/lelf
      - name: Upload system volume
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: svfs
          path: svfs.img
      - name: Upload LVM image
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        uses: actions/upload-artifact@v2
        with:
          name: lvm
          path: lvm.img
      - name: Test OS
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        timeout-minutes: 1
        run: |
          sed -i "s/loader.bin/loader.bin ci/" grub.cfg
          make run-grub-nographic
  style:
    runs-on: ubuntu-20.04
    needs: toolchain
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          key: toolchain-ubuntu-20.04-${{ hashFiles('tools/Makefile') }}
          path: tools/toolchain
      - name: Format code
        run: make format
      - name: Check if there are any changes
        run: git diff --exit-code
  analyze:
    runs-on: ubuntu-20.04
    needs: toolchain
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          key: toolchain-ubuntu-20.04-${{ hashFiles('tools/Makefile') }}
          path: tools/toolchain
      - name: Analyze
        run: make analyze -j2
